name: Release Github Packages

on:
  push:
    branches: [ master ]

jobs:

  build-stable:
    name: Build Stable Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:latest

  build-slim:
    name: Build Slim Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor }}/${{ secrets.image }}:slim2
          curl -L -O https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
          tar -zxvf dist_linux.tar.gz
          script -q -c "./dist_linux/docker-slim --debug version"
          script -q -c "./dist_linux/docker-slim build --target ghcr.io/${{ github.actor }}/${{ secrets.image }}:slim2 --http-probe-off --tag ghcr.io/${{ github.actor }}/${{ secrets.image }}:slim"
          docker push ghcr.io/${{ github.actor }}/${{ secrets.image }}:slim