name: Test Github Packages

on:
  pull_request:
    branches: [ master ]

jobs:

  build-stable:
    name: Build Stable Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.USER }}/${{ secrets.IMAGE }}:test
          docker-compose -f .github/docker-compose-test.yml up -d
          sleep 5
          curl --fail localhost:8080 | exit 1

  build-slim:
    name: Build Slim Image
    runs-on: ubuntu-latest
    needs: ["build-stable"]
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GH_TOKEN }}
      - run: |
          docker build . -t ghcr.io/${{ github.USER }}/${{ secrets.IMAGE }}:testslim
          curl -L -O https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
          tar -zxvf dist_linux.tar.gz
          script -q -c "./dist_linux/docker-slim --debug version"
          script -q -c "./dist_linux/docker-slim build --target ghcr.io/${{ github.USER }}/${{ secrets.IMAGE }}:testslim --http-probe-off --tag ghcr.io/${{ github.USER }}/${{ secrets.IMAGE }}:testslim2"
          docker-compose -f .github/docker-compose-test-slim.yml up -d
          sleep 5
          curl --fail localhost:8080 | exit 1
